export type HookType = 'ON_VIEW_ELEMENT_CLICK'
  | 'ON_VIEW_ELEMENT_DBCLICK'
  | 'ON_VIEW_KEY_DOWN'
  | 'ON_VIEW_RENDER'
  | 'ON_VIEW_RENDERED'
  | 'ON_VIEW_MOUNTED'
  | 'ON_VIEW_FILE_CHANGE'
  | 'ON_VIEW_BEFORE_CONVERT'

export type ActionName = 'view.refresh' | 'view.reveal-line'
